// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7W8uDtuLoGde-M1kNh-sxie_cgvCYIE8',
    appId: '1:373599257522:web:b80fa5ae30b8e6108b9aab',
    messagingSenderId: '373599257522',
    projectId: 'mercadinho-vinicius',
    authDomain: 'mercadinho-vinicius.firebaseapp.com',
    storageBucket: 'mercadinho-vinicius.firebasestorage.app',
    measurementId: 'G-ML24GNZ8J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDixTEHOaxiUskpD1Xfab-AnTjKb-fhsYE',
    appId: '1:373599257522:android:a0c2e95a2f7ad98c8b9aab',
    messagingSenderId: '373599257522',
    projectId: 'mercadinho-vinicius',
    storageBucket: 'mercadinho-vinicius.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwAXBx93_sMIAElCoZQxyKSkm8Mcmn3YU',
    appId: '1:373599257522:ios:5397b442664746eb8b9aab',
    messagingSenderId: '373599257522',
    projectId: 'mercadinho-vinicius',
    storageBucket: 'mercadinho-vinicius.firebasestorage.app',
    iosBundleId: 'com.example.avaliacao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwAXBx93_sMIAElCoZQxyKSkm8Mcmn3YU',
    appId: '1:373599257522:ios:5397b442664746eb8b9aab',
    messagingSenderId: '373599257522',
    projectId: 'mercadinho-vinicius',
    storageBucket: 'mercadinho-vinicius.firebasestorage.app',
    iosBundleId: 'com.example.avaliacao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7W8uDtuLoGde-M1kNh-sxie_cgvCYIE8',
    appId: '1:373599257522:web:2c352715cd4102db8b9aab',
    messagingSenderId: '373599257522',
    projectId: 'mercadinho-vinicius',
    authDomain: 'mercadinho-vinicius.firebaseapp.com',
    storageBucket: 'mercadinho-vinicius.firebasestorage.app',
    measurementId: 'G-TWJQTLT31C',
  );
}
